### PR TITLE
Bug 1039497 modified AppInstall.js

### PR DESCRIPTION
**Pull request by tsl143**
Replaced the AppInstall.js from https://github.com/mozilla/mortar-appinstall/tree/master/src

### CODE REVIEW

**Comment by sole** [comment]
hey did you test this out? I'm curious to see if the template can be used by other people with the current instructions :)

**Comment by tsl143** [comment]
yes the install button is behaving as expected

**Comment by sole** [comment]
Well it is not actually behaving as expected, but the issue is in AppInstall.js - I'll sort it out myself!
Thanks for your help!

**Comment by sole** [comment]
OK @tsl143 here's how I fixed it!
The previous version of AppInstall didn't work well in the browser but it did work in the test environment (node) because the `_window` object was assigned default values.

I fixed so that it tries to detect if we're running in a browser and if so, use the `window` object---which in this context is `this`. To have a greater peace of mind I also made sure that the `document` property exists in this `this`.

You can see the diff here: https://github.com/mozilla/mortar-appinstall/commit/a8298183241460fb6f6c6439d568387dff16cfe1

**Pull request merged**
